/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Overview = {
  hero?: CaseImage;
  themes?: Array<
    {
      _key: string;
    } & ScreenTab
  >;
  lead?: string;
};

export type ScrollViewport = {
  src?: string;
  alt?: string;
};

export type Hotspots = {
  src?: string;
  alt?: string;
  callouts?: Array<
    {
      _key: string;
    } & HotspotCallout
  >;
};

export type Outcome = {
  copy?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
};

export type LabsStat = {
  _type: 'labsStat';
  value?: string;
  label?: string;
};

export type LabsStrand = {
  _type: 'labsStrand';
  name?: string;
  desc?: string;
};

export type Stat = {
  _type: 'stat';
  value?: string;
  label?: string;
};

export type HotspotCallout = {
  _type: 'hotspotCallout';
  x?: number;
  y?: number;
  label?: string;
  body?: string;
};

export type ScreenTab = {
  _type: 'screenTab';
  id?: string;
  label?: string;
  src?: string;
  alt?: string;
};

export type CaseImage = {
  _type: 'caseImage';
  src?: string;
  alt?: string;
  label?: string;
};

export type CaseStudy = {
  _type: 'caseStudy';
  eyebrow?: string;
  overview?: Overview;
  problem?: string;
  process?: string;
  screens?: Array<
    {
      _key: string;
    } & CaseImage
  >;
  mobile?: Array<
    {
      _key: string;
    } & CaseImage
  >;
  scrollViewport?: ScrollViewport;
  hotspots?: Hotspots;
  switcher?: Array<
    {
      _key: string;
    } & ScreenTab
  >;
  outcome?: Outcome;
};

export type Labs = {
  _id: string;
  _type: 'labs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  about?: Array<
    {
      _key: string;
    } & LabsStrand
  >;
  stats?: Array<
    {
      _key: string;
    } & LabsStat
  >;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  order?: number;
  cover?: string;
  tags?: Array<string>;
  date?: string;
  title?: string;
  headline?: string;
  description?: string;
  year?: string;
  client?: string;
  timeline?: string;
  status?: 'Closed' | 'Finished' | 'In progress';
  caseStudy?: CaseStudy;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Overview
  | ScrollViewport
  | Hotspots
  | Outcome
  | LabsStat
  | LabsStrand
  | Stat
  | HotspotCallout
  | ScreenTab
  | CaseImage
  | CaseStudy
  | Labs
  | Project
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc) {    "slug": slug.current, name, order, cover, tags, date, title, headline,    description, year, client, timeline, status, caseStudy  }
export type PROJECTS_QUERY_RESULT = Array<{
  slug: string | null;
  name: string | null;
  order: number | null;
  cover: string | null;
  tags: Array<string> | null;
  date: string | null;
  title: string | null;
  headline: string | null;
  description: string | null;
  year: string | null;
  client: string | null;
  timeline: string | null;
  status: 'Closed' | 'Finished' | 'In progress' | null;
  caseStudy: CaseStudy | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)] { "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    "slug": slug.current, name, order, cover, tags, date, title, headline,    description, year, client, timeline, status, caseStudy  }
export type PROJECT_QUERY_RESULT = {
  slug: string | null;
  name: string | null;
  order: number | null;
  cover: string | null;
  tags: Array<string> | null;
  date: string | null;
  title: string | null;
  headline: string | null;
  description: string | null;
  year: string | null;
  client: string | null;
  timeline: string | null;
  status: 'Closed' | 'Finished' | 'In progress' | null;
  caseStudy: CaseStudy | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: LABS_QUERY
// Query: *[_type == "labs"][0] { about, stats }
export type LABS_QUERY_RESULT = {
  about: Array<
    {
      _key: string;
    } & LabsStrand
  > | null;
  stats: Array<
    {
      _key: string;
    } & LabsStat
  > | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(order asc) {\n    "slug": slug.current, name, order, cover, tags, date, title, headline,\n    description, year, client, timeline, status, caseStudy\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)] { "slug": slug.current }\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    "slug": slug.current, name, order, cover, tags, date, title, headline,\n    description, year, client, timeline, status, caseStudy\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "labs"][0] { about, stats }\n': LABS_QUERY_RESULT;
  }
}
